### PR TITLE
Upgrade to jqueryui 1.10.4.

### PR DESCRIPTION
**Pull request by maethu**
- [x]  Use minified jqueryui.css
- [x] Human manual test

### CODE REVIEW

**Comment by maethu** [comment]
@rpatterson any chance to get this?

**Comment by rpatterson** [comment]
@maethu I'm not actually actively involved ATM and can't review this.  Maybe ask on the plone-devel list?

**Comment by jensens** [comment]
reading the commit history @bsuttor and @toutpt are deeper involved (aka maintainer).
looking at pypi youll find another bunch of people with release permissions at the bottom at https://pypi.python.org/pypi/collective.js.jqueryui/1.10.4

**Comment by maethu** [comment]
May @bsuttor or @toutpt take a look at this one??

I would also really appreciate a new release!

**Comment by bsuttor** [comment]
It seems version of this Plone package is little confuse with version of js plguin.
I think it's better to make different version between js plugin version and Plone package version. Indeed Sometimes we have to change Plone source code without changing js and make a release.
 
Version of js plugin must be in README
So I will make a 2.0 release if nobody have problem with this ;)

**Comment by bsuttor** [comment]
Done !
https://pypi.python.org/pypi/collective.js.jqueryui/2.0.0

**Comment by maethu** [comment]
Nice :+1: Thank you! :sparkles:

**Pull request merged**
